[versions]
agp = "8.5.0"
android-test-extensions = "1.4.0"
androidJunit5Plugin = "1.10.0.0"
androidx-activityCompose = "1.9.0"
androidx-data-store = "1.1.1"
compose = "1.6.8"
crashlytics = "3.0.2"
detekt = "1.23.6"
firebaseBom = "33.1.1"
firebaseAnalytics = "22.0.2"
firebaseCrashlytics = "19.0.2"
googleServices = "4.4.2"
jetbrains-compose = "1.6.11"
junit = "5.10.2"
koin = "3.5.6"
koin-compose = "1.1.5"
kotlin = "2.0.0"
kotlinx-immutable = "0.3.7"
kotlinxDatetime = "0.6.0"
mokkery = "2.0.0"
pre-compose = "1.6.0"
realm = "2.0.0"
reorderable = "2.1.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-data-store-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-data-store" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit5-android-test-compose = { module = "de.mannodermaus.junit5:android-test-compose", version.ref = "android-test-extensions" }
junit5-android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "android-test-extensions" }
junit5-android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "android-test-extensions" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
pre-compose = { module = "moe.tlaster:precompose", version.ref = "pre-compose" }
pre-compose-koin = { module = "moe.tlaster:precompose-koin", version.ref = "pre-compose" }
pre-compose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "pre-compose" }
realm-library-base = { module = "io.realm.kotlin:library-base", version.ref = "realm" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidJunit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5Plugin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
crashlytics = {id ="com.google.firebase.crashlytics", version.ref = "crashlytics" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
googleServices = {id ="com.google.gms.google-services", version.ref = "googleServices" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }