[versions]
agp = "8.3.1"
androidx-activityCompose = "1.8.2"
compose = "1.6.4"
jetbrains-compose = "1.6.1"
compose-material3 = "1.2.1"
koin = "3.5.3"
kotlin = "1.9.23"
kotlinx-immutable = "0.3.7"
sql-delight = "1.5.5"
stability-report = "1.1.0"
pre-compose = "1.5.11"
koin-compose = "1.1.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-viewmodel = { module = "io.insert-koin:koin-android-viewmodel", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
sql-delight = { module = "com.squareup.sqldelight:runtime", version.ref = "sql-delight" }
sql-delight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sql-delight" }
sql-delight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sql-delight" }
pre-compose = {module = "moe.tlaster:precompose", version.ref = "pre-compose" }
pre-compose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "pre-compose" }
pre-compose-koin = {module = "moe.tlaster:precompose-koin", version.ref = "pre-compose" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
sqlDelight = { id = "com.squareup.sqldelight", version.ref = "sql-delight" }
stabilityReport = { id = "dev.shreyaspatil.compose-compiler-report-generator", version.ref = "stability-report" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }


