name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Reverted this to get builds going, iOS currently won't build due to
    # missing SQLDelight dependencies on iOS target.
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'timerx.jks'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Set secrets
      run: |
        echo "storeFile=timerx.jks" >> keystore.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
        echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> keystore.properties

    - name: Check
      run: ./gradlew check --warning-mode all

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive Android APK
      uses: actions/upload-artifact@v4
      with:
        name: Android debug build
        path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
