name: OSX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 24
          check-latest: true
          distribution: zulu
          cache: gradle

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'intervallum.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Set store path
        run: echo "storePath=${{ steps.decode_keystore.outputs.filePath }}" >> local.properties

      - name: Build with Gradle
        run: ./gradlew packageDmg packageReleaseDmg packagePkg packageReleasePkg

      - name: Archive DMG Debug
        uses: actions/upload-artifact@v4
        with:
          name: DMG-Debug
          path: ./shared/build/compose/binaries/main/dmg/com.intervallum-**.dmg
          if-no-files-found: error

      - name: Archive DMG Release
        uses: actions/upload-artifact@v4
        with:
          name: DMG-Release
          path: ./shared/build/compose/binaries/main-release/dmg/com.intervallum-**.dmg
          if-no-files-found: error

      - name: Archive DMG Debug
        uses: actions/upload-artifact@v4
        with:
          name: PKG-Debug
          path: ./shared/build/compose/binaries/main/pkg/com.intervallum-**.pkg
          if-no-files-found: error

      - name: Archive DMG Release
        uses: actions/upload-artifact@v4
        with:
          name: PKG-Release
          path: ./shared/build/compose/binaries/main-release/pkg/com.intervallum-**.pkg
          if-no-files-found: error
