name: wasm

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 17
          cache: 'gradle'

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'intervallum.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Set store path
        run: echo "storePath=${{ steps.decode_keystore.outputs.filePath }}" >> local.properties

      - name: Build wasm
        run: ./gradlew wasmJsBrowserDistribution

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          path: 'shared/build/dist/wasmJs/productionExecutable'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
