name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          check-latest: true
          java-version: 17
          cache: 'gradle'

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'intervallum.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Set store path
        run: echo "storePath=${{ steps.decode_keystore.outputs.filePath }}" >> local.properties

      - name: Build
        run: |
          ./gradlew packageExe packageReleaseExe packageMsi packageReleaseMsi --warning-mode all

      - name: Archive Exe Release
        uses: actions/upload-artifact@v4
        with:
          name: Exe-Release
          path: shared/build/compose/binaries/main-release/exe/com.intervallum**.exe
          if-no-files-found: error

      - name: Archive Exe Debug
        uses: actions/upload-artifact@v4
        with:
          name: Exe-Debug
          path: shared/build/compose/binaries/main/exe/com.intervallum**.exe
          if-no-files-found: error

      - name: Archive MSI Release
        uses: actions/upload-artifact@v4
        with:
          name: MSI-Release
          path: shared/build/compose/binaries/main-release/msi/com.intervallum**.msi
          if-no-files-found: error

      - name: Archive MSI Debug
        uses: actions/upload-artifact@v4
        with:
          name: MSI-Debug
          path: shared/build/compose/binaries/main/msi/com.intervallum**.msi
          if-no-files-found: error
