name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          check-latest: true
          java-version: 17
          cache: 'gradle'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set blank secrets
        run: |
          echo "storeFile=123" >> keystore.properties
          echo "storePassword=123" >> keystore.properties
          echo "keyPassword=123" >> keystore.properties
          echo "keyAlias=123" >> keystore.properties

      - name: Build
        run: |
          ./gradlew packageExe
          cat build\compose\logs\packageExe\jpackage*
